#!/bin/bash
# Martin Häggström 200207

function InstallPrograms() {
    apt install -y \
    curl \
    git \
    keychain \
    nmap \
    openssh-server
}

function CloneRepositories() {

	for repository in vimrc.git Swedish_locale.git Gpgfile.git vpn.git
	do
	    dir=$(echo "${repository}" | sed 's/\.git//')
	    if [ -d "$dir" ]
	    then
		echo "$dir exists, remove it first."
	    else
		git clone https://github.com/sparmcgit/${repository}
		fi
	done
}

function InstallScripts() {

    cp vpn/vpn /usr/local/bin
    cp Gpgfile/gpgfile /usr/local/bin
}

function Setup() {

cat <<-EOF
================================
cp vimrc/.vimrc to $HOME

EOF

echo "================================"
cat Swedish_locale/README.md | sed 's/\\//g'
echo ""
}

InstallPrograms
CloneRepositories
InstallScripts
Setup
